# Generated by Django 4.0.5 on 2022-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220603_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_id',
            field=models.CharField(default=18, max_length=18),
            preserve_default=False,
        ),
    ]
