# Generated by Django 3.1.2 on 2022-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_post_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message_id',
            field=models.CharField(default='18', max_length=18),
        ),
    ]
